version: "3"

services:
  frontend-client:
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ravindu0823/musify-client:1.1.2
    ports:
      - "5173:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
