version: "3"

services:
  client:
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ravindu0823/musify-client:1.1.2
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  server:
    container_name: server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ravindu0823/musify-server:1.1.2
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
